---
#========================================
#   Global Settings
#========================================
global_settings:
  intersight_fqdn: intersight.com
  tags:
    - key: "Module"
      value: "easy-imm"
    - key: "Version"
      value: "4.2.11-20250122215055407"
